version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: smart-rabbit-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - smart_rabbit_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
  build:
    context: .
    dockerfile: Dockerfile
  container_name: smart-rabbit-app
  restart: always
  env_file:
    - .env
  ports:
    - "3005:3005"
  depends_on:
    - db
