version: "3.9"

services:
  smart-rabbit:
    build:
      context: .
      dockerfile: Dockerfile
    image: smart_rabbit:latest
    container_name: smart-rabbit
    ports:
      - "3005:3005"
    restart: unless-stopped
